create database cafeteria;

use cafeteria;

CREATE TABLE categorias (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO categorias (nombre) VALUES
('Desayuno Americano'),
('Desayuno Continental'),
('Bocadillos'),
('Crepas'),
('Tostadas'),
('Empanadas'),
('Bagels'),
('Wraps'),
('Burritos'),
('Sushi'),
('Noodles'),
('Arroces'),
('Parrilladas'),
('Carnes'),
('Mariscos'),
('Enchiladas'),
('Tacos'),
('Quesadillas'),
('Fajitas'),
('Sopes'),
('Ceviche'),
('Sushi'),
('Sashimi'),
('Tempura'),
('Ramen'),
('Curry'),
('Tofu'),
('Ensaladas de Frutas'),
('Helados Artesanales'),
('Malteadas'),
('Crepas Dulces'),
('Waffles'),
('Gelato'),
('Milkshakes'),
('Postres Caseros'),
('Cupcakes'),
('Chocolate'),
('Café de Especialidad'),
('Café Orgánico'),
('Café de Origen'),
('Café Descafeinado'),
('Té de Hierbas'),
('Té con Leche'),
('Smoothies'),
('Licores'),
('Cervezas Artesanales'),
('Vinos'),
('Cocteles'),
('Bebidas sin Alcohol'),
('Infusiones'),
('Agua Mineral'),
('Bebidas Energéticas'),
('Zumos Detox'),
('Sopas Cremas'),
('Sopas de Verduras'),
('Sopas Picantes'),
('Palomitas de Maíz'),
('Papas Fritas'),
('Nachos'),
('Alitas de Pollo'),
('Rollitos Primavera'),
('Aperitivos'),
('Sándwiches Gourmet'),
('Sándwiches Vegetarianos'),
('Sándwiches Veganos'),
('Sándwiches de Pollo'),
('Sándwiches de Pavo'),
('Sándwiches de Carne'),
('Sándwiches de Pescado'),
('Sándwiches de Queso'),
('Ensaladas Mixtas'),
('Ensaladas César'),
('Ensaladas Griegas'),
('Ensaladas de Pollo'),
('Ensaladas de Salmón'),
('Ensaladas de Atún'),
('Ensaladas de Quinoa'),
('Ensaladas de Garbanzos'),
('Ensaladas de Pasta'),
('Ensaladas de Frutos Secos'),
('Ensaladas Veganas'),
('Ensaladas sin Gluten'),
('Ensaladas de Frutas'),
('Ensaladas Caprese'),
('Ensaladas de Tomate'),
('Ensaladas de Aguacate'),
('Ensaladas de Kale'),
('Ensaladas de Espinacas'),
('Ensaladas de Remolacha'),
('Ensaladas de Mango'),
('Ensaladas de Sandía'),
('Ensaladas de Pepino'),
('Ensaladas de Zanahoria');

CREATE TABLE productos(
	id INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR (100) NOT NULL,
	referencia VARCHAR (100) NOT NULL,
	precio INT not null,
	peso INT not null,
	id_categoria INT NOT NULL,
	stock INT not null,
	fecha_creacion DATE not NULL,
	PRIMARY KEY (id)
);

CREATE TABLE ventas(
	id INT NOT NULL AUTO_INCREMENT,
	cantidad INT not null,
	id_producto INT NOT NULL,
	PRIMARY KEY (id)
);

alter table productos add constraINT ´productos_fk_1´ foreign key(id_categoria) references categorias(id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ventas add constraINT ´ventas_fk_1´ foreign key(id_producto) references productos(id) ON DELETE CASCADE ON UPDATE CASCADE;